ifeq ($(_THEOS_TARGET_LOADED),)
_THEOS_TARGET_LOADED := 1
THEOS_TARGET_NAME := uikitformac

_THEOS_TARGET_PLATFORM_NAME := macosx
_THEOS_TARGET_PLATFORM_SDK_NAME := MacOSX
_THEOS_TARGET_PLATFORM_SWIFT_NAME := apple-ios
_THEOS_TARGET_PLATFORM_SWIFT_SUFFIX := -macabi
_THEOS_TARGET_DARWIN_BUNDLE_TYPE := hierarchial
_THEOS_DARWIN_CAN_USE_MODULES := $(_THEOS_TRUE)
_THEOS_TARGET_USE_CLANG_TARGET_FLAG := $(_THEOS_TRUE)
_THEOS_TARGET_USE_APPLE_LIBSWIFT := $(_THEOS_TRUE)

TARGET_INSTALL_REMOTE := $(_THEOS_FALSE)
_THEOS_TARGET_DEFAULT_PACKAGE_FORMAT := pkg

include $(THEOS_MAKE_PATH)/targets/_common/darwin_head.mk

ARCHS ?= x86_64
NEUTRAL_ARCH := x86_64

_THEOS_TARGET_DEFAULT_OS_DEPLOYMENT_VERSION := 13.0

include $(THEOS_MAKE_PATH)/targets/_common/darwin_tail.mk

_THEOS_UIKITFORMAC_INCLUDEFLAGS := -isystem $(SYSROOT)/System/iOSSupport/usr/include -iframework $(SYSROOT)/System/iOSSupport/System/Library/Frameworks
_THEOS_UIKITFORMAC_SWIFTINCLUDEFLAGS := -Xcc -isystem -Xcc $(SYSROOT)/System/iOSSupport/usr/include -Fsystem $(SYSROOT)/System/iOSSupport/System/Library/Frameworks
_THEOS_UIKITFORMAC_LDFLAGS := -L$(SYSROOT)/System/iOSSupport/usr/lib -L$(dir $(shell type -p $(TARGET_SWIFT)))../lib/swift/uikitformac

_THEOS_TARGET_CFLAGS += $(_THEOS_UIKITFORMAC_INCLUDEFLAGS)
_THEOS_TARGET_SWIFTFLAGS += $(_THEOS_UIKITFORMAC_SWIFTINCLUDEFLAGS)
_THEOS_TARGET_LDFLAGS += $(_THEOS_UIKITFORMAC_INCLUDEFLAGS) $(_THEOS_UIKITFORMAC_LDFLAGS)
endif
