ifeq ($(FW_PLATFORM_LOADED),)
FW_PLATFORM_LOADED := 1

TARGET ?= arm-apple-darwin9
SDKBINPATH ?= /usr/bin
SYSROOT ?= /var/sdk

PREFIX := $(SDKBINPATH)/$(TARGET)-

TARGET_CC ?= $(PREFIX)gcc
TARGET_CXX ?= $(PREFIX)g++
TARGET_STRIP ?= strip
TARGET_CODESIGN_ALLOCATE ?= codesign_allocate
TARGET_CODESIGN ?= ldid

SDKFLAGS := -isysroot $(SYSROOT)
SDK_CFLAGS := $(SDKFLAGS)
SDK_LDFLAGS := $(SDKFLAGS)

DU_EXCLUDE = --exclude

endif
