ifeq ($(_THEOS_TARGET_LOADED),)
_THEOS_TARGET_LOADED := 1
THEOS_TARGET_NAME := linux

ifneq ($(words $(_THEOS_TARGET_ARGS)),0)
CROSS_COMPILE := $(firstword $(_THEOS_TARGET_ARGS))-
endif 

TARGET_CC ?= $(CROSS_COMPILE)gcc
TARGET_CXX ?= $(CROSS_COMPILE)g++
TARGET_LD ?= $(CROSS_COMPILE)g++
TARGET_STRIP ?= $(CROSS_COMPILE)strip
TARGET_STRIP_FLAGS ?=
TARGET_CODESIGN_ALLOCATE ?=
TARGET_CODESIGN ?=
TARGET_CODESIGN_FLAGS ?=

include $(THEOS_MAKE_PATH)/targets/_common/linux.mk

SDKFLAGS :=
endif
